services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - peerprep-network

volumes:
  redis_data:

networks:
  peerprep-network:
    external: true
