services:
  code_runner:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # access to host docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

networks:
  peerprep-network:
    external: true
