name: Root CI Pipeline
run-name: PeerPrep
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
jobs:
  run-backend:
    uses: ./.github/workflows/backend_ci.yml
